name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      ImageName: ${{ secrets.DOCKER_USERNAME }}/jri-bot
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Setup Go environment
      uses: actions/setup-go@v5.6.0
      
    - uses: actions/checkout@v4
    
    - name: Set image tags
      run: |
        echo "TIMED_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/jri-bot:$(date +%s)" >> $GITHUB_ENV
        echo "LATEST_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/jri-bot:latest" >> $GITHUB_ENV
    
    - name: Build image
      run: docker build -t ${{ env.TIMED_IMAGE_NAME }} -t ${{ env.LATEST_IMAGE_NAME }} .
    
    - name: Push image
      run: | 
        docker push ${{ env.TIMED_IMAGE_NAME }}
        docker push ${{ env.LATEST_IMAGE_NAME }}
    
